/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.Condition = factory(root.OxdServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Condition model module.
   * @module model/Condition
   * @version 4.0
   */

  /**
   * Constructs a new <code>Condition</code>.
   * @alias module:model/Condition
   * @class
   * @param httpMethods {Array.<String>} 
   * @param scopes {Array.<String>} 
   * @param scopeExpression {Array.<String>} 
   * @param ticketScopes {Array.<String>} 
   */
  var exports = function(httpMethods, scopes, scopeExpression, ticketScopes) {
    var _this = this;

    _this['httpMethods'] = httpMethods;
    _this['scopes'] = scopes;
    _this['scope_expression'] = scopeExpression;
    _this['ticketScopes'] = ticketScopes;
  };

  /**
   * Constructs a <code>Condition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Condition} obj Optional instance to populate.
   * @return {module:model/Condition} The populated <code>Condition</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('httpMethods')) {
        obj['httpMethods'] = ApiClient.convertToType(data['httpMethods'], ['String']);
      }
      if (data.hasOwnProperty('scopes')) {
        obj['scopes'] = ApiClient.convertToType(data['scopes'], ['String']);
      }
      if (data.hasOwnProperty('scope_expression')) {
        obj['scope_expression'] = ApiClient.convertToType(data['scope_expression'], ['String']);
      }
      if (data.hasOwnProperty('ticketScopes')) {
        obj['ticketScopes'] = ApiClient.convertToType(data['ticketScopes'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} httpMethods
   */
  exports.prototype['httpMethods'] = undefined;
  /**
   * @member {Array.<String>} scopes
   */
  exports.prototype['scopes'] = undefined;
  /**
   * @member {Array.<String>} scope_expression
   */
  exports.prototype['scope_expression'] = undefined;
  /**
   * @member {Array.<String>} ticketScopes
   */
  exports.prototype['ticketScopes'] = undefined;



  return exports;
}));


