/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetauthorizationurlCustomParameters'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetauthorizationurlCustomParameters'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.GetAuthorizationUrlParams = factory(root.OxdServer.ApiClient, root.OxdServer.GetauthorizationurlCustomParameters);
  }
}(this, function(ApiClient, GetauthorizationurlCustomParameters) {
  'use strict';




  /**
   * The GetAuthorizationUrlParams model module.
   * @module model/GetAuthorizationUrlParams
   * @version 4.0
   */

  /**
   * Constructs a new <code>GetAuthorizationUrlParams</code>.
   * @alias module:model/GetAuthorizationUrlParams
   * @class
   * @param oxdId {String} 
   */
  var exports = function(oxdId) {
    var _this = this;

    _this['oxd_id'] = oxdId;





  };

  /**
   * Constructs a <code>GetAuthorizationUrlParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAuthorizationUrlParams} obj Optional instance to populate.
   * @return {module:model/GetAuthorizationUrlParams} The populated <code>GetAuthorizationUrlParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('oxd_id')) {
        obj['oxd_id'] = ApiClient.convertToType(data['oxd_id'], 'String');
      }
      if (data.hasOwnProperty('scope')) {
        obj['scope'] = ApiClient.convertToType(data['scope'], ['String']);
      }
      if (data.hasOwnProperty('acr_values')) {
        obj['acr_values'] = ApiClient.convertToType(data['acr_values'], ['String']);
      }
      if (data.hasOwnProperty('prompt')) {
        obj['prompt'] = ApiClient.convertToType(data['prompt'], 'String');
      }
      if (data.hasOwnProperty('authorization_redirect_uri')) {
        obj['authorization_redirect_uri'] = ApiClient.convertToType(data['authorization_redirect_uri'], 'String');
      }
      if (data.hasOwnProperty('custom_parameters')) {
        obj['custom_parameters'] = GetauthorizationurlCustomParameters.constructFromObject(data['custom_parameters']);
      }
    }
    return obj;
  }

  /**
   * @member {String} oxd_id
   */
  exports.prototype['oxd_id'] = undefined;
  /**
   * @member {Array.<String>} scope
   */
  exports.prototype['scope'] = undefined;
  /**
   * @member {Array.<String>} acr_values
   */
  exports.prototype['acr_values'] = undefined;
  /**
   * @member {String} prompt
   */
  exports.prototype['prompt'] = undefined;
  /**
   * @member {String} authorization_redirect_uri
   */
  exports.prototype['authorization_redirect_uri'] = undefined;
  /**
   * @member {module:model/GetauthorizationurlCustomParameters} custom_parameters
   */
  exports.prototype['custom_parameters'] = undefined;



  return exports;
}));


