/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.GetAuthorizationUrlResponse = factory(root.OxdServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetAuthorizationUrlResponse model module.
   * @module model/GetAuthorizationUrlResponse
   * @version 4.0
   */

  /**
   * Constructs a new <code>GetAuthorizationUrlResponse</code>.
   * @alias module:model/GetAuthorizationUrlResponse
   * @class
   * @param authorizationUrl {String} 
   */
  var exports = function(authorizationUrl) {
    var _this = this;

    _this['authorization_url'] = authorizationUrl;
  };

  /**
   * Constructs a <code>GetAuthorizationUrlResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAuthorizationUrlResponse} obj Optional instance to populate.
   * @return {module:model/GetAuthorizationUrlResponse} The populated <code>GetAuthorizationUrlResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('authorization_url')) {
        obj['authorization_url'] = ApiClient.convertToType(data['authorization_url'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} authorization_url
   */
  exports.prototype['authorization_url'] = undefined;



  return exports;
}));


