/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.GetDiscoveryResponse = factory(root.OxdServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetDiscoveryResponse model module.
   * @module model/GetDiscoveryResponse
   * @version 4.0
   */

  /**
   * Constructs a new <code>GetDiscoveryResponse</code>.
   * @alias module:model/GetDiscoveryResponse
   * @class
   */
  var exports = function() {
    var _this = this;














































  };

  /**
   * Constructs a <code>GetDiscoveryResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetDiscoveryResponse} obj Optional instance to populate.
   * @return {module:model/GetDiscoveryResponse} The populated <code>GetDiscoveryResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('issuer')) {
        obj['issuer'] = ApiClient.convertToType(data['issuer'], 'String');
      }
      if (data.hasOwnProperty('authorization_endpoint')) {
        obj['authorization_endpoint'] = ApiClient.convertToType(data['authorization_endpoint'], 'String');
      }
      if (data.hasOwnProperty('token_endpoint')) {
        obj['token_endpoint'] = ApiClient.convertToType(data['token_endpoint'], 'String');
      }
      if (data.hasOwnProperty('token_revocation_endpoint')) {
        obj['token_revocation_endpoint'] = ApiClient.convertToType(data['token_revocation_endpoint'], 'String');
      }
      if (data.hasOwnProperty('user_info_endpoint')) {
        obj['user_info_endpoint'] = ApiClient.convertToType(data['user_info_endpoint'], 'String');
      }
      if (data.hasOwnProperty('client_info_endpoint')) {
        obj['client_info_endpoint'] = ApiClient.convertToType(data['client_info_endpoint'], 'String');
      }
      if (data.hasOwnProperty('check_session_iframe')) {
        obj['check_session_iframe'] = ApiClient.convertToType(data['check_session_iframe'], 'String');
      }
      if (data.hasOwnProperty('end_session_endpoint')) {
        obj['end_session_endpoint'] = ApiClient.convertToType(data['end_session_endpoint'], 'String');
      }
      if (data.hasOwnProperty('jwks_uri')) {
        obj['jwks_uri'] = ApiClient.convertToType(data['jwks_uri'], 'String');
      }
      if (data.hasOwnProperty('registration_endpoint')) {
        obj['registration_endpoint'] = ApiClient.convertToType(data['registration_endpoint'], 'String');
      }
      if (data.hasOwnProperty('id_generation_endpoint')) {
        obj['id_generation_endpoint'] = ApiClient.convertToType(data['id_generation_endpoint'], 'String');
      }
      if (data.hasOwnProperty('introspection_endpoint')) {
        obj['introspection_endpoint'] = ApiClient.convertToType(data['introspection_endpoint'], 'String');
      }
      if (data.hasOwnProperty('scopes_supported')) {
        obj['scopes_supported'] = ApiClient.convertToType(data['scopes_supported'], ['String']);
      }
      if (data.hasOwnProperty('response_types_supported')) {
        obj['response_types_supported'] = ApiClient.convertToType(data['response_types_supported'], ['String']);
      }
      if (data.hasOwnProperty('grant_types_supported')) {
        obj['grant_types_supported'] = ApiClient.convertToType(data['grant_types_supported'], ['String']);
      }
      if (data.hasOwnProperty('acr_values_supported')) {
        obj['acr_values_supported'] = ApiClient.convertToType(data['acr_values_supported'], ['String']);
      }
      if (data.hasOwnProperty('subject_types_supported')) {
        obj['subject_types_supported'] = ApiClient.convertToType(data['subject_types_supported'], ['String']);
      }
      if (data.hasOwnProperty('user_info_signing_alg_values_supported')) {
        obj['user_info_signing_alg_values_supported'] = ApiClient.convertToType(data['user_info_signing_alg_values_supported'], ['String']);
      }
      if (data.hasOwnProperty('user_info_encryption_alg_values_supported')) {
        obj['user_info_encryption_alg_values_supported'] = ApiClient.convertToType(data['user_info_encryption_alg_values_supported'], ['String']);
      }
      if (data.hasOwnProperty('user_info_encryption_enc_values_supported')) {
        obj['user_info_encryption_enc_values_supported'] = ApiClient.convertToType(data['user_info_encryption_enc_values_supported'], ['String']);
      }
      if (data.hasOwnProperty('id_token_signing_alg_values_supported')) {
        obj['id_token_signing_alg_values_supported'] = ApiClient.convertToType(data['id_token_signing_alg_values_supported'], ['String']);
      }
      if (data.hasOwnProperty('id_token_encryption_alg_values_supported')) {
        obj['id_token_encryption_alg_values_supported'] = ApiClient.convertToType(data['id_token_encryption_alg_values_supported'], ['String']);
      }
      if (data.hasOwnProperty('id_token_encryption_enc_values_supported')) {
        obj['id_token_encryption_enc_values_supported'] = ApiClient.convertToType(data['id_token_encryption_enc_values_supported'], ['String']);
      }
      if (data.hasOwnProperty('request_object_signing_alg_values_supported')) {
        obj['request_object_signing_alg_values_supported'] = ApiClient.convertToType(data['request_object_signing_alg_values_supported'], ['String']);
      }
      if (data.hasOwnProperty('request_object_encryption_alg_values_supported')) {
        obj['request_object_encryption_alg_values_supported'] = ApiClient.convertToType(data['request_object_encryption_alg_values_supported'], ['String']);
      }
      if (data.hasOwnProperty('request_object_encryption_enc_values_supported')) {
        obj['request_object_encryption_enc_values_supported'] = ApiClient.convertToType(data['request_object_encryption_enc_values_supported'], ['String']);
      }
      if (data.hasOwnProperty('token_endpoint_auth_methods_supported')) {
        obj['token_endpoint_auth_methods_supported'] = ApiClient.convertToType(data['token_endpoint_auth_methods_supported'], ['String']);
      }
      if (data.hasOwnProperty('token_endpoint_auth_signing_alg_values_supported')) {
        obj['token_endpoint_auth_signing_alg_values_supported'] = ApiClient.convertToType(data['token_endpoint_auth_signing_alg_values_supported'], ['String']);
      }
      if (data.hasOwnProperty('display_values_supported')) {
        obj['display_values_supported'] = ApiClient.convertToType(data['display_values_supported'], ['String']);
      }
      if (data.hasOwnProperty('claim_types_supported')) {
        obj['claim_types_supported'] = ApiClient.convertToType(data['claim_types_supported'], ['String']);
      }
      if (data.hasOwnProperty('claims_supported')) {
        obj['claims_supported'] = ApiClient.convertToType(data['claims_supported'], ['String']);
      }
      if (data.hasOwnProperty('id_token_token_binding_cnf_values_supported')) {
        obj['id_token_token_binding_cnf_values_supported'] = ApiClient.convertToType(data['id_token_token_binding_cnf_values_supported'], ['String']);
      }
      if (data.hasOwnProperty('service_documentation')) {
        obj['service_documentation'] = ApiClient.convertToType(data['service_documentation'], 'String');
      }
      if (data.hasOwnProperty('claims_locales_supported')) {
        obj['claims_locales_supported'] = ApiClient.convertToType(data['claims_locales_supported'], ['String']);
      }
      if (data.hasOwnProperty('ui_locales_supported')) {
        obj['ui_locales_supported'] = ApiClient.convertToType(data['ui_locales_supported'], ['String']);
      }
      if (data.hasOwnProperty('claims_parameter_supported')) {
        obj['claims_parameter_supported'] = ApiClient.convertToType(data['claims_parameter_supported'], 'Boolean');
      }
      if (data.hasOwnProperty('request_parameter_supported')) {
        obj['request_parameter_supported'] = ApiClient.convertToType(data['request_parameter_supported'], 'Boolean');
      }
      if (data.hasOwnProperty('request_uri_parameter_supported')) {
        obj['request_uri_parameter_supported'] = ApiClient.convertToType(data['request_uri_parameter_supported'], 'Boolean');
      }
      if (data.hasOwnProperty('require_request_uri_registration')) {
        obj['require_request_uri_registration'] = ApiClient.convertToType(data['require_request_uri_registration'], 'Boolean');
      }
      if (data.hasOwnProperty('tls_client_certificate_bound_access_tokens')) {
        obj['tls_client_certificate_bound_access_tokens'] = ApiClient.convertToType(data['tls_client_certificate_bound_access_tokens'], 'Boolean');
      }
      if (data.hasOwnProperty('front_channel_logout_supported')) {
        obj['front_channel_logout_supported'] = ApiClient.convertToType(data['front_channel_logout_supported'], 'Boolean');
      }
      if (data.hasOwnProperty('front_channel_logout_session_supported')) {
        obj['front_channel_logout_session_supported'] = ApiClient.convertToType(data['front_channel_logout_session_supported'], 'Boolean');
      }
      if (data.hasOwnProperty('op_policy_uri')) {
        obj['op_policy_uri'] = ApiClient.convertToType(data['op_policy_uri'], 'String');
      }
      if (data.hasOwnProperty('op_tos_uri')) {
        obj['op_tos_uri'] = ApiClient.convertToType(data['op_tos_uri'], 'String');
      }
      if (data.hasOwnProperty('scope_to_claims_mapping')) {
        obj['scope_to_claims_mapping'] = ApiClient.convertToType(data['scope_to_claims_mapping'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {String} issuer
   */
  exports.prototype['issuer'] = undefined;
  /**
   * @member {String} authorization_endpoint
   */
  exports.prototype['authorization_endpoint'] = undefined;
  /**
   * @member {String} token_endpoint
   */
  exports.prototype['token_endpoint'] = undefined;
  /**
   * @member {String} token_revocation_endpoint
   */
  exports.prototype['token_revocation_endpoint'] = undefined;
  /**
   * @member {String} user_info_endpoint
   */
  exports.prototype['user_info_endpoint'] = undefined;
  /**
   * @member {String} client_info_endpoint
   */
  exports.prototype['client_info_endpoint'] = undefined;
  /**
   * @member {String} check_session_iframe
   */
  exports.prototype['check_session_iframe'] = undefined;
  /**
   * @member {String} end_session_endpoint
   */
  exports.prototype['end_session_endpoint'] = undefined;
  /**
   * @member {String} jwks_uri
   */
  exports.prototype['jwks_uri'] = undefined;
  /**
   * @member {String} registration_endpoint
   */
  exports.prototype['registration_endpoint'] = undefined;
  /**
   * @member {String} id_generation_endpoint
   */
  exports.prototype['id_generation_endpoint'] = undefined;
  /**
   * @member {String} introspection_endpoint
   */
  exports.prototype['introspection_endpoint'] = undefined;
  /**
   * @member {Array.<String>} scopes_supported
   */
  exports.prototype['scopes_supported'] = undefined;
  /**
   * @member {Array.<String>} response_types_supported
   */
  exports.prototype['response_types_supported'] = undefined;
  /**
   * @member {Array.<String>} grant_types_supported
   */
  exports.prototype['grant_types_supported'] = undefined;
  /**
   * @member {Array.<String>} acr_values_supported
   */
  exports.prototype['acr_values_supported'] = undefined;
  /**
   * @member {Array.<String>} subject_types_supported
   */
  exports.prototype['subject_types_supported'] = undefined;
  /**
   * @member {Array.<String>} user_info_signing_alg_values_supported
   */
  exports.prototype['user_info_signing_alg_values_supported'] = undefined;
  /**
   * @member {Array.<String>} user_info_encryption_alg_values_supported
   */
  exports.prototype['user_info_encryption_alg_values_supported'] = undefined;
  /**
   * @member {Array.<String>} user_info_encryption_enc_values_supported
   */
  exports.prototype['user_info_encryption_enc_values_supported'] = undefined;
  /**
   * @member {Array.<String>} id_token_signing_alg_values_supported
   */
  exports.prototype['id_token_signing_alg_values_supported'] = undefined;
  /**
   * @member {Array.<String>} id_token_encryption_alg_values_supported
   */
  exports.prototype['id_token_encryption_alg_values_supported'] = undefined;
  /**
   * @member {Array.<String>} id_token_encryption_enc_values_supported
   */
  exports.prototype['id_token_encryption_enc_values_supported'] = undefined;
  /**
   * @member {Array.<String>} request_object_signing_alg_values_supported
   */
  exports.prototype['request_object_signing_alg_values_supported'] = undefined;
  /**
   * @member {Array.<String>} request_object_encryption_alg_values_supported
   */
  exports.prototype['request_object_encryption_alg_values_supported'] = undefined;
  /**
   * @member {Array.<String>} request_object_encryption_enc_values_supported
   */
  exports.prototype['request_object_encryption_enc_values_supported'] = undefined;
  /**
   * @member {Array.<String>} token_endpoint_auth_methods_supported
   */
  exports.prototype['token_endpoint_auth_methods_supported'] = undefined;
  /**
   * @member {Array.<String>} token_endpoint_auth_signing_alg_values_supported
   */
  exports.prototype['token_endpoint_auth_signing_alg_values_supported'] = undefined;
  /**
   * @member {Array.<String>} display_values_supported
   */
  exports.prototype['display_values_supported'] = undefined;
  /**
   * @member {Array.<String>} claim_types_supported
   */
  exports.prototype['claim_types_supported'] = undefined;
  /**
   * @member {Array.<String>} claims_supported
   */
  exports.prototype['claims_supported'] = undefined;
  /**
   * @member {Array.<String>} id_token_token_binding_cnf_values_supported
   */
  exports.prototype['id_token_token_binding_cnf_values_supported'] = undefined;
  /**
   * @member {String} service_documentation
   */
  exports.prototype['service_documentation'] = undefined;
  /**
   * @member {Array.<String>} claims_locales_supported
   */
  exports.prototype['claims_locales_supported'] = undefined;
  /**
   * @member {Array.<String>} ui_locales_supported
   */
  exports.prototype['ui_locales_supported'] = undefined;
  /**
   * @member {Boolean} claims_parameter_supported
   */
  exports.prototype['claims_parameter_supported'] = undefined;
  /**
   * @member {Boolean} request_parameter_supported
   */
  exports.prototype['request_parameter_supported'] = undefined;
  /**
   * @member {Boolean} request_uri_parameter_supported
   */
  exports.prototype['request_uri_parameter_supported'] = undefined;
  /**
   * @member {Boolean} require_request_uri_registration
   */
  exports.prototype['require_request_uri_registration'] = undefined;
  /**
   * @member {Boolean} tls_client_certificate_bound_access_tokens
   */
  exports.prototype['tls_client_certificate_bound_access_tokens'] = undefined;
  /**
   * @member {Boolean} front_channel_logout_supported
   */
  exports.prototype['front_channel_logout_supported'] = undefined;
  /**
   * @member {Boolean} front_channel_logout_session_supported
   */
  exports.prototype['front_channel_logout_session_supported'] = undefined;
  /**
   * @member {String} op_policy_uri
   */
  exports.prototype['op_policy_uri'] = undefined;
  /**
   * @member {String} op_tos_uri
   */
  exports.prototype['op_tos_uri'] = undefined;
  /**
   * @member {Object} scope_to_claims_mapping
   */
  exports.prototype['scope_to_claims_mapping'] = undefined;



  return exports;
}));


