/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.GetJwksParams = factory(root.OxdServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetJwksParams model module.
   * @module model/GetJwksParams
   * @version 4.0
   */

  /**
   * Constructs a new <code>GetJwksParams</code>.
   * @alias module:model/GetJwksParams
   * @class
   * @param opHost {String} 
   */
  var exports = function(opHost) {
    var _this = this;

    _this['op_host'] = opHost;

  };

  /**
   * Constructs a <code>GetJwksParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetJwksParams} obj Optional instance to populate.
   * @return {module:model/GetJwksParams} The populated <code>GetJwksParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('op_host')) {
        obj['op_host'] = ApiClient.convertToType(data['op_host'], 'String');
      }
      if (data.hasOwnProperty('op_discovery_path')) {
        obj['op_discovery_path'] = ApiClient.convertToType(data['op_discovery_path'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} op_host
   */
  exports.prototype['op_host'] = undefined;
  /**
   * @member {String} op_discovery_path
   */
  exports.prototype['op_discovery_path'] = undefined;



  return exports;
}));


