/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/JsonWebKey'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./JsonWebKey'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.GetJwksResponse = factory(root.OxdServer.ApiClient, root.OxdServer.JsonWebKey);
  }
}(this, function(ApiClient, JsonWebKey) {
  'use strict';




  /**
   * The GetJwksResponse model module.
   * @module model/GetJwksResponse
   * @version 4.0
   */

  /**
   * Constructs a new <code>GetJwksResponse</code>.
   * @alias module:model/GetJwksResponse
   * @class
   * @param keys {Array.<module:model/JsonWebKey>} 
   */
  var exports = function(keys) {
    var _this = this;

    _this['keys'] = keys;
  };

  /**
   * Constructs a <code>GetJwksResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetJwksResponse} obj Optional instance to populate.
   * @return {module:model/GetJwksResponse} The populated <code>GetJwksResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('keys')) {
        obj['keys'] = ApiClient.convertToType(data['keys'], [JsonWebKey]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/JsonWebKey>} keys
   */
  exports.prototype['keys'] = undefined;



  return exports;
}));


