/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.GetTokensByCodeResponse = factory(root.OxdServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetTokensByCodeResponse model module.
   * @module model/GetTokensByCodeResponse
   * @version 4.0
   */

  /**
   * Constructs a new <code>GetTokensByCodeResponse</code>.
   * @alias module:model/GetTokensByCodeResponse
   * @class
   * @param accessToken {String} 
   * @param expiresIn {Number} 
   * @param idToken {String} 
   * @param refreshToken {String} 
   * @param idTokenClaims {Object} 
   */
  var exports = function(accessToken, expiresIn, idToken, refreshToken, idTokenClaims) {
    var _this = this;

    _this['access_token'] = accessToken;
    _this['expires_in'] = expiresIn;
    _this['id_token'] = idToken;
    _this['refresh_token'] = refreshToken;
    _this['id_token_claims'] = idTokenClaims;
  };

  /**
   * Constructs a <code>GetTokensByCodeResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetTokensByCodeResponse} obj Optional instance to populate.
   * @return {module:model/GetTokensByCodeResponse} The populated <code>GetTokensByCodeResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('access_token')) {
        obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
      }
      if (data.hasOwnProperty('expires_in')) {
        obj['expires_in'] = ApiClient.convertToType(data['expires_in'], 'Number');
      }
      if (data.hasOwnProperty('id_token')) {
        obj['id_token'] = ApiClient.convertToType(data['id_token'], 'String');
      }
      if (data.hasOwnProperty('refresh_token')) {
        obj['refresh_token'] = ApiClient.convertToType(data['refresh_token'], 'String');
      }
      if (data.hasOwnProperty('id_token_claims')) {
        obj['id_token_claims'] = ApiClient.convertToType(data['id_token_claims'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {String} access_token
   */
  exports.prototype['access_token'] = undefined;
  /**
   * @member {Number} expires_in
   */
  exports.prototype['expires_in'] = undefined;
  /**
   * @member {String} id_token
   */
  exports.prototype['id_token'] = undefined;
  /**
   * @member {String} refresh_token
   */
  exports.prototype['refresh_token'] = undefined;
  /**
   * @member {Object} id_token_claims
   */
  exports.prototype['id_token_claims'] = undefined;



  return exports;
}));


