/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.IntrospectRptResponse = factory(root.OxdServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The IntrospectRptResponse model module.
   * @module model/IntrospectRptResponse
   * @version 4.0
   */

  /**
   * Constructs a new <code>IntrospectRptResponse</code>.
   * @alias module:model/IntrospectRptResponse
   * @class
   * @param active {Boolean} 
   * @param exp {Number} number of seconds since January 1 1970 UTC, indicating when this token will expire
   * @param iat {Number} number of seconds since January 1 1970 UTC, indicating when the token was issued at
   * @param nbf {Number} number of seconds since January 1 1970 UTC, indicating when the token not to be used before
   * @param clientId {String} 
   * @param aud {String} 
   * @param iss {String} 
   * @param permissions {Array.<Object>} 
   */
  var exports = function(active, exp, iat, nbf, clientId, aud, iss, permissions) {
    var _this = this;

    _this['active'] = active;
    _this['exp'] = exp;
    _this['iat'] = iat;
    _this['nbf'] = nbf;
    _this['client_id'] = clientId;

    _this['aud'] = aud;
    _this['iss'] = iss;

    _this['permissions'] = permissions;
  };

  /**
   * Constructs a <code>IntrospectRptResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IntrospectRptResponse} obj Optional instance to populate.
   * @return {module:model/IntrospectRptResponse} The populated <code>IntrospectRptResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('active')) {
        obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
      }
      if (data.hasOwnProperty('exp')) {
        obj['exp'] = ApiClient.convertToType(data['exp'], 'Number');
      }
      if (data.hasOwnProperty('iat')) {
        obj['iat'] = ApiClient.convertToType(data['iat'], 'Number');
      }
      if (data.hasOwnProperty('nbf')) {
        obj['nbf'] = ApiClient.convertToType(data['nbf'], 'Number');
      }
      if (data.hasOwnProperty('client_id')) {
        obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
      }
      if (data.hasOwnProperty('sub')) {
        obj['sub'] = ApiClient.convertToType(data['sub'], 'String');
      }
      if (data.hasOwnProperty('aud')) {
        obj['aud'] = ApiClient.convertToType(data['aud'], 'String');
      }
      if (data.hasOwnProperty('iss')) {
        obj['iss'] = ApiClient.convertToType(data['iss'], 'String');
      }
      if (data.hasOwnProperty('jti')) {
        obj['jti'] = ApiClient.convertToType(data['jti'], 'String');
      }
      if (data.hasOwnProperty('permissions')) {
        obj['permissions'] = ApiClient.convertToType(data['permissions'], [Object]);
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} active
   */
  exports.prototype['active'] = undefined;
  /**
   * number of seconds since January 1 1970 UTC, indicating when this token will expire
   * @member {Number} exp
   */
  exports.prototype['exp'] = undefined;
  /**
   * number of seconds since January 1 1970 UTC, indicating when the token was issued at
   * @member {Number} iat
   */
  exports.prototype['iat'] = undefined;
  /**
   * number of seconds since January 1 1970 UTC, indicating when the token not to be used before
   * @member {Number} nbf
   */
  exports.prototype['nbf'] = undefined;
  /**
   * @member {String} client_id
   */
  exports.prototype['client_id'] = undefined;
  /**
   * @member {String} sub
   */
  exports.prototype['sub'] = undefined;
  /**
   * @member {String} aud
   */
  exports.prototype['aud'] = undefined;
  /**
   * @member {String} iss
   */
  exports.prototype['iss'] = undefined;
  /**
   * @member {String} jti
   */
  exports.prototype['jti'] = undefined;
  /**
   * @member {Array.<Object>} permissions
   */
  exports.prototype['permissions'] = undefined;



  return exports;
}));


