/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.RegisterSiteParams = factory(root.OxdServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RegisterSiteParams model module.
   * @module model/RegisterSiteParams
   * @version 4.0
   */

  /**
   * Constructs a new <code>RegisterSiteParams</code>.
   * @alias module:model/RegisterSiteParams
   * @class
   * @param authorizationRedirectUri {String} 
   */
  var exports = function(authorizationRedirectUri) {
    var _this = this;

    _this['authorization_redirect_uri'] = authorizationRedirectUri;
























  };

  /**
   * Constructs a <code>RegisterSiteParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegisterSiteParams} obj Optional instance to populate.
   * @return {module:model/RegisterSiteParams} The populated <code>RegisterSiteParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('authorization_redirect_uri')) {
        obj['authorization_redirect_uri'] = ApiClient.convertToType(data['authorization_redirect_uri'], 'String');
      }
      if (data.hasOwnProperty('op_host')) {
        obj['op_host'] = ApiClient.convertToType(data['op_host'], 'String');
      }
      if (data.hasOwnProperty('post_logout_redirect_uris')) {
        obj['post_logout_redirect_uris'] = ApiClient.convertToType(data['post_logout_redirect_uris'], ['String']);
      }
      if (data.hasOwnProperty('application_type')) {
        obj['application_type'] = ApiClient.convertToType(data['application_type'], 'String');
      }
      if (data.hasOwnProperty('response_types')) {
        obj['response_types'] = ApiClient.convertToType(data['response_types'], ['String']);
      }
      if (data.hasOwnProperty('grant_types')) {
        obj['grant_types'] = ApiClient.convertToType(data['grant_types'], ['String']);
      }
      if (data.hasOwnProperty('scope')) {
        obj['scope'] = ApiClient.convertToType(data['scope'], ['String']);
      }
      if (data.hasOwnProperty('acr_values')) {
        obj['acr_values'] = ApiClient.convertToType(data['acr_values'], ['String']);
      }
      if (data.hasOwnProperty('client_name')) {
        obj['client_name'] = ApiClient.convertToType(data['client_name'], 'String');
      }
      if (data.hasOwnProperty('client_jwks_uri')) {
        obj['client_jwks_uri'] = ApiClient.convertToType(data['client_jwks_uri'], 'String');
      }
      if (data.hasOwnProperty('client_token_endpoint_auth_method')) {
        obj['client_token_endpoint_auth_method'] = ApiClient.convertToType(data['client_token_endpoint_auth_method'], 'String');
      }
      if (data.hasOwnProperty('client_request_uris')) {
        obj['client_request_uris'] = ApiClient.convertToType(data['client_request_uris'], ['String']);
      }
      if (data.hasOwnProperty('client_frontchannel_logout_uris')) {
        obj['client_frontchannel_logout_uris'] = ApiClient.convertToType(data['client_frontchannel_logout_uris'], ['String']);
      }
      if (data.hasOwnProperty('client_sector_identifier_uri')) {
        obj['client_sector_identifier_uri'] = ApiClient.convertToType(data['client_sector_identifier_uri'], 'String');
      }
      if (data.hasOwnProperty('contacts')) {
        obj['contacts'] = ApiClient.convertToType(data['contacts'], ['String']);
      }
      if (data.hasOwnProperty('redirect_uris')) {
        obj['redirect_uris'] = ApiClient.convertToType(data['redirect_uris'], ['String']);
      }
      if (data.hasOwnProperty('ui_locales')) {
        obj['ui_locales'] = ApiClient.convertToType(data['ui_locales'], ['String']);
      }
      if (data.hasOwnProperty('claims_locales')) {
        obj['claims_locales'] = ApiClient.convertToType(data['claims_locales'], ['String']);
      }
      if (data.hasOwnProperty('claims_redirect_uri')) {
        obj['claims_redirect_uri'] = ApiClient.convertToType(data['claims_redirect_uri'], ['String']);
      }
      if (data.hasOwnProperty('client_id')) {
        obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
      }
      if (data.hasOwnProperty('client_secret')) {
        obj['client_secret'] = ApiClient.convertToType(data['client_secret'], 'String');
      }
      if (data.hasOwnProperty('trusted_client')) {
        obj['trusted_client'] = ApiClient.convertToType(data['trusted_client'], 'Boolean');
      }
      if (data.hasOwnProperty('access_token_as_jwt')) {
        obj['access_token_as_jwt'] = ApiClient.convertToType(data['access_token_as_jwt'], 'Boolean');
      }
      if (data.hasOwnProperty('access_token_signing_alg')) {
        obj['access_token_signing_alg'] = ApiClient.convertToType(data['access_token_signing_alg'], 'String');
      }
      if (data.hasOwnProperty('rpt_as_jwt')) {
        obj['rpt_as_jwt'] = ApiClient.convertToType(data['rpt_as_jwt'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} authorization_redirect_uri
   */
  exports.prototype['authorization_redirect_uri'] = undefined;
  /**
   * If missing, must be present in defaults
   * @member {String} op_host
   */
  exports.prototype['op_host'] = undefined;
  /**
   * @member {Array.<String>} post_logout_redirect_uris
   */
  exports.prototype['post_logout_redirect_uris'] = undefined;
  /**
   * @member {String} application_type
   */
  exports.prototype['application_type'] = undefined;
  /**
   * @member {Array.<String>} response_types
   */
  exports.prototype['response_types'] = undefined;
  /**
   * @member {Array.<String>} grant_types
   */
  exports.prototype['grant_types'] = undefined;
  /**
   * @member {Array.<String>} scope
   */
  exports.prototype['scope'] = undefined;
  /**
   * @member {Array.<String>} acr_values
   */
  exports.prototype['acr_values'] = undefined;
  /**
   * oxd will generate its own non-human readable name by default if client_name is not specified
   * @member {String} client_name
   */
  exports.prototype['client_name'] = undefined;
  /**
   * @member {String} client_jwks_uri
   */
  exports.prototype['client_jwks_uri'] = undefined;
  /**
   * @member {String} client_token_endpoint_auth_method
   */
  exports.prototype['client_token_endpoint_auth_method'] = undefined;
  /**
   * @member {Array.<String>} client_request_uris
   */
  exports.prototype['client_request_uris'] = undefined;
  /**
   * @member {Array.<String>} client_frontchannel_logout_uris
   */
  exports.prototype['client_frontchannel_logout_uris'] = undefined;
  /**
   * @member {String} client_sector_identifier_uri
   */
  exports.prototype['client_sector_identifier_uri'] = undefined;
  /**
   * @member {Array.<String>} contacts
   */
  exports.prototype['contacts'] = undefined;
  /**
   * @member {Array.<String>} redirect_uris
   */
  exports.prototype['redirect_uris'] = undefined;
  /**
   * @member {Array.<String>} ui_locales
   */
  exports.prototype['ui_locales'] = undefined;
  /**
   * @member {Array.<String>} claims_locales
   */
  exports.prototype['claims_locales'] = undefined;
  /**
   * @member {Array.<String>} claims_redirect_uri
   */
  exports.prototype['claims_redirect_uri'] = undefined;
  /**
   * client id of existing client, ignores all other parameters and skips new client registration forcing to use existing client (client_secret is required if this parameter is set)
   * @member {String} client_id
   */
  exports.prototype['client_id'] = undefined;
  /**
   * client secret of existing client, must be used together with client_id
   * @member {String} client_secret
   */
  exports.prototype['client_secret'] = undefined;
  /**
   * specifies whether client is trusted. Default value is false.
   * @member {Boolean} trusted_client
   */
  exports.prototype['trusted_client'] = undefined;
  /**
   * specifies whether access_token should be return as JWT or not. Default value is false.
   * @member {Boolean} access_token_as_jwt
   */
  exports.prototype['access_token_as_jwt'] = undefined;
  /**
   * sets signing algorithm used for JWT signing. Valid values are none, HS256, HS384, HS512, RS256, RS384, RS512, ES256, ES384, ES512
   * @member {String} access_token_signing_alg
   */
  exports.prototype['access_token_signing_alg'] = undefined;
  /**
   * specifies whether RPT should be return as JWT or not. Default value is false.
   * @member {Boolean} rpt_as_jwt
   */
  exports.prototype['rpt_as_jwt'] = undefined;



  return exports;
}));


