/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.RegisterSiteResponse = factory(root.OxdServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RegisterSiteResponse model module.
   * @module model/RegisterSiteResponse
   * @version 4.0
   */

  /**
   * Constructs a new <code>RegisterSiteResponse</code>.
   * @alias module:model/RegisterSiteResponse
   * @class
   * @param oxdId {String} 
   * @param opHost {String} 
   */
  var exports = function(oxdId, opHost) {
    var _this = this;

    _this['oxd_id'] = oxdId;
    _this['op_host'] = opHost;







  };

  /**
   * Constructs a <code>RegisterSiteResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegisterSiteResponse} obj Optional instance to populate.
   * @return {module:model/RegisterSiteResponse} The populated <code>RegisterSiteResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('oxd_id')) {
        obj['oxd_id'] = ApiClient.convertToType(data['oxd_id'], 'String');
      }
      if (data.hasOwnProperty('op_host')) {
        obj['op_host'] = ApiClient.convertToType(data['op_host'], 'String');
      }
      if (data.hasOwnProperty('client_id')) {
        obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
      }
      if (data.hasOwnProperty('client_name')) {
        obj['client_name'] = ApiClient.convertToType(data['client_name'], 'String');
      }
      if (data.hasOwnProperty('client_secret')) {
        obj['client_secret'] = ApiClient.convertToType(data['client_secret'], 'String');
      }
      if (data.hasOwnProperty('client_registration_access_token')) {
        obj['client_registration_access_token'] = ApiClient.convertToType(data['client_registration_access_token'], 'String');
      }
      if (data.hasOwnProperty('client_registration_client_uri')) {
        obj['client_registration_client_uri'] = ApiClient.convertToType(data['client_registration_client_uri'], 'String');
      }
      if (data.hasOwnProperty('client_id_issued_at')) {
        obj['client_id_issued_at'] = ApiClient.convertToType(data['client_id_issued_at'], 'Number');
      }
      if (data.hasOwnProperty('client_secret_expires_at')) {
        obj['client_secret_expires_at'] = ApiClient.convertToType(data['client_secret_expires_at'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} oxd_id
   */
  exports.prototype['oxd_id'] = undefined;
  /**
   * @member {String} op_host
   */
  exports.prototype['op_host'] = undefined;
  /**
   * @member {String} client_id
   */
  exports.prototype['client_id'] = undefined;
  /**
   * @member {String} client_name
   */
  exports.prototype['client_name'] = undefined;
  /**
   * @member {String} client_secret
   */
  exports.prototype['client_secret'] = undefined;
  /**
   * @member {String} client_registration_access_token
   */
  exports.prototype['client_registration_access_token'] = undefined;
  /**
   * @member {String} client_registration_client_uri
   */
  exports.prototype['client_registration_client_uri'] = undefined;
  /**
   * @member {Number} client_id_issued_at
   */
  exports.prototype['client_id_issued_at'] = undefined;
  /**
   * @member {Number} client_secret_expires_at
   */
  exports.prototype['client_secret_expires_at'] = undefined;



  return exports;
}));


