/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Condition'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Condition'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.RsResource = factory(root.OxdServer.ApiClient, root.OxdServer.Condition);
  }
}(this, function(ApiClient, Condition) {
  'use strict';




  /**
   * The RsResource model module.
   * @module model/RsResource
   * @version 4.0
   */

  /**
   * Constructs a new <code>RsResource</code>.
   * @alias module:model/RsResource
   * @class
   * @param path {String} 
   * @param conditions {Array.<module:model/Condition>} 
   */
  var exports = function(path, conditions) {
    var _this = this;

    _this['path'] = path;
    _this['conditions'] = conditions;
  };

  /**
   * Constructs a <code>RsResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RsResource} obj Optional instance to populate.
   * @return {module:model/RsResource} The populated <code>RsResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('path')) {
        obj['path'] = ApiClient.convertToType(data['path'], 'String');
      }
      if (data.hasOwnProperty('conditions')) {
        obj['conditions'] = ApiClient.convertToType(data['conditions'], [Condition]);
      }
    }
    return obj;
  }

  /**
   * @member {String} path
   */
  exports.prototype['path'] = undefined;
  /**
   * @member {Array.<module:model/Condition>} conditions
   */
  exports.prototype['conditions'] = undefined;



  return exports;
}));


