/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.UmaRpGetRptResponse = factory(root.OxdServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UmaRpGetRptResponse model module.
   * @module model/UmaRpGetRptResponse
   * @version 4.0
   */

  /**
   * Constructs a new <code>UmaRpGetRptResponse</code>.
   * @alias module:model/UmaRpGetRptResponse
   * @class
   * @param pct {String} 
   * @param updated {Boolean} 
   * @param accessToken {String} 
   * @param tokenType {String} 
   */
  var exports = function(pct, updated, accessToken, tokenType) {
    var _this = this;

    _this['pct'] = pct;
    _this['updated'] = updated;
    _this['access_token'] = accessToken;
    _this['token_type'] = tokenType;
  };

  /**
   * Constructs a <code>UmaRpGetRptResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UmaRpGetRptResponse} obj Optional instance to populate.
   * @return {module:model/UmaRpGetRptResponse} The populated <code>UmaRpGetRptResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pct')) {
        obj['pct'] = ApiClient.convertToType(data['pct'], 'String');
      }
      if (data.hasOwnProperty('updated')) {
        obj['updated'] = ApiClient.convertToType(data['updated'], 'Boolean');
      }
      if (data.hasOwnProperty('access_token')) {
        obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
      }
      if (data.hasOwnProperty('token_type')) {
        obj['token_type'] = ApiClient.convertToType(data['token_type'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} pct
   */
  exports.prototype['pct'] = undefined;
  /**
   * @member {Boolean} updated
   */
  exports.prototype['updated'] = undefined;
  /**
   * @member {String} access_token
   */
  exports.prototype['access_token'] = undefined;
  /**
   * @member {String} token_type
   */
  exports.prototype['token_type'] = undefined;



  return exports;
}));


