/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.UmaRsCheckAccessResponse = factory(root.OxdServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UmaRsCheckAccessResponse model module.
   * @module model/UmaRsCheckAccessResponse
   * @version 4.0
   */

  /**
   * Constructs a new <code>UmaRsCheckAccessResponse</code>.
   * @alias module:model/UmaRsCheckAccessResponse
   * @class
   * @param access {String} Possible values are granted, denied
   * @param ticket {String} 
   */
  var exports = function(access, ticket) {
    var _this = this;

    _this['access'] = access;
    _this['ticket'] = ticket;
  };

  /**
   * Constructs a <code>UmaRsCheckAccessResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UmaRsCheckAccessResponse} obj Optional instance to populate.
   * @return {module:model/UmaRsCheckAccessResponse} The populated <code>UmaRsCheckAccessResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('access')) {
        obj['access'] = ApiClient.convertToType(data['access'], 'String');
      }
      if (data.hasOwnProperty('ticket')) {
        obj['ticket'] = ApiClient.convertToType(data['ticket'], 'String');
      }
    }
    return obj;
  }

  /**
   * Possible values are granted, denied
   * @member {String} access
   */
  exports.prototype['access'] = undefined;
  /**
   * @member {String} ticket
   */
  exports.prototype['ticket'] = undefined;



  return exports;
}));


