/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.UmaRpGetRptParams = factory(root.OxdServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UmaRpGetRptParams model module.
   * @module model/UmaRpGetRptParams
   * @version 4.0
   */

  /**
   * Constructs a new <code>UmaRpGetRptParams</code>.
   * @alias module:model/UmaRpGetRptParams
   * @class
   * @param oxdId {String} 
   * @param ticket {String} 
   * @param claimToken {String} 
   * @param claimTokenFormat {String} 
   * @param pct {String} 
   * @param rpt {String} 
   * @param scope {Array.<String>} 
   * @param state {String} 
   */
  var exports = function(oxdId, ticket, claimToken, claimTokenFormat, pct, rpt, scope, state) {
    var _this = this;

    _this['oxd_id'] = oxdId;
    _this['ticket'] = ticket;
    _this['claim_token'] = claimToken;
    _this['claim_token_format'] = claimTokenFormat;
    _this['pct'] = pct;
    _this['rpt'] = rpt;
    _this['scope'] = scope;
    _this['state'] = state;
  };

  /**
   * Constructs a <code>UmaRpGetRptParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UmaRpGetRptParams} obj Optional instance to populate.
   * @return {module:model/UmaRpGetRptParams} The populated <code>UmaRpGetRptParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('oxd_id')) {
        obj['oxd_id'] = ApiClient.convertToType(data['oxd_id'], 'String');
      }
      if (data.hasOwnProperty('ticket')) {
        obj['ticket'] = ApiClient.convertToType(data['ticket'], 'String');
      }
      if (data.hasOwnProperty('claim_token')) {
        obj['claim_token'] = ApiClient.convertToType(data['claim_token'], 'String');
      }
      if (data.hasOwnProperty('claim_token_format')) {
        obj['claim_token_format'] = ApiClient.convertToType(data['claim_token_format'], 'String');
      }
      if (data.hasOwnProperty('pct')) {
        obj['pct'] = ApiClient.convertToType(data['pct'], 'String');
      }
      if (data.hasOwnProperty('rpt')) {
        obj['rpt'] = ApiClient.convertToType(data['rpt'], 'String');
      }
      if (data.hasOwnProperty('scope')) {
        obj['scope'] = ApiClient.convertToType(data['scope'], ['String']);
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} oxd_id
   */
  exports.prototype['oxd_id'] = undefined;
  /**
   * @member {String} ticket
   */
  exports.prototype['ticket'] = undefined;
  /**
   * @member {String} claim_token
   */
  exports.prototype['claim_token'] = undefined;
  /**
   * @member {String} claim_token_format
   */
  exports.prototype['claim_token_format'] = undefined;
  /**
   * @member {String} pct
   */
  exports.prototype['pct'] = undefined;
  /**
   * @member {String} rpt
   */
  exports.prototype['rpt'] = undefined;
  /**
   * @member {Array.<String>} scope
   */
  exports.prototype['scope'] = undefined;
  /**
   * @member {String} state
   */
  exports.prototype['state'] = undefined;



  return exports;
}));


