/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RsResource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RsResource'));
  } else {
    // Browser globals (root is window)
    if (!root.OxdServer) {
      root.OxdServer = {};
    }
    root.OxdServer.UmaRsProtectParams = factory(root.OxdServer.ApiClient, root.OxdServer.RsResource);
  }
}(this, function(ApiClient, RsResource) {
  'use strict';




  /**
   * The UmaRsProtectParams model module.
   * @module model/UmaRsProtectParams
   * @version 4.0
   */

  /**
   * Constructs a new <code>UmaRsProtectParams</code>.
   * @alias module:model/UmaRsProtectParams
   * @class
   * @param oxdId {String} 
   * @param overwrite {Boolean} 
   * @param resources {Array.<module:model/RsResource>} 
   */
  var exports = function(oxdId, overwrite, resources) {
    var _this = this;

    _this['oxd_id'] = oxdId;
    _this['overwrite'] = overwrite;
    _this['resources'] = resources;
  };

  /**
   * Constructs a <code>UmaRsProtectParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UmaRsProtectParams} obj Optional instance to populate.
   * @return {module:model/UmaRsProtectParams} The populated <code>UmaRsProtectParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('oxd_id')) {
        obj['oxd_id'] = ApiClient.convertToType(data['oxd_id'], 'String');
      }
      if (data.hasOwnProperty('overwrite')) {
        obj['overwrite'] = ApiClient.convertToType(data['overwrite'], 'Boolean');
      }
      if (data.hasOwnProperty('resources')) {
        obj['resources'] = ApiClient.convertToType(data['resources'], [RsResource]);
      }
    }
    return obj;
  }

  /**
   * @member {String} oxd_id
   */
  exports.prototype['oxd_id'] = undefined;
  /**
   * @member {Boolean} overwrite
   */
  exports.prototype['overwrite'] = undefined;
  /**
   * @member {Array.<module:model/RsResource>} resources
   */
  exports.prototype['resources'] = undefined;



  return exports;
}));


