/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OxdServer);
  }
}(this, function(expect, OxdServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OxdServer.GetAuthorizationUrlParams();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetAuthorizationUrlParams', function() {
    it('should create an instance of GetAuthorizationUrlParams', function() {
      // uncomment below and update the code to test GetAuthorizationUrlParams
      //var instance = new OxdServer.GetAuthorizationUrlParams();
      //expect(instance).to.be.a(OxdServer.GetAuthorizationUrlParams);
    });

    it('should have the property oxdId (base name: "oxd_id")', function() {
      // uncomment below and update the code to test the property oxdId
      //var instance = new OxdServer.GetAuthorizationUrlParams();
      //expect(instance).to.be();
    });

    it('should have the property scope (base name: "scope")', function() {
      // uncomment below and update the code to test the property scope
      //var instance = new OxdServer.GetAuthorizationUrlParams();
      //expect(instance).to.be();
    });

    it('should have the property acrValues (base name: "acr_values")', function() {
      // uncomment below and update the code to test the property acrValues
      //var instance = new OxdServer.GetAuthorizationUrlParams();
      //expect(instance).to.be();
    });

    it('should have the property prompt (base name: "prompt")', function() {
      // uncomment below and update the code to test the property prompt
      //var instance = new OxdServer.GetAuthorizationUrlParams();
      //expect(instance).to.be();
    });

    it('should have the property authorizationRedirectUri (base name: "authorization_redirect_uri")', function() {
      // uncomment below and update the code to test the property authorizationRedirectUri
      //var instance = new OxdServer.GetAuthorizationUrlParams();
      //expect(instance).to.be();
    });

    it('should have the property customParameters (base name: "custom_parameters")', function() {
      // uncomment below and update the code to test the property customParameters
      //var instance = new OxdServer.GetAuthorizationUrlParams();
      //expect(instance).to.be();
    });

  });

}));
