/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OxdServer);
  }
}(this, function(expect, OxdServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OxdServer.GetClientTokenParams();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetClientTokenParams', function() {
    it('should create an instance of GetClientTokenParams', function() {
      // uncomment below and update the code to test GetClientTokenParams
      //var instance = new OxdServer.GetClientTokenParams();
      //expect(instance).to.be.a(OxdServer.GetClientTokenParams);
    });

    it('should have the property opHost (base name: "op_host")', function() {
      // uncomment below and update the code to test the property opHost
      //var instance = new OxdServer.GetClientTokenParams();
      //expect(instance).to.be();
    });

    it('should have the property opDiscoveryPath (base name: "op_discovery_path")', function() {
      // uncomment below and update the code to test the property opDiscoveryPath
      //var instance = new OxdServer.GetClientTokenParams();
      //expect(instance).to.be();
    });

    it('should have the property scope (base name: "scope")', function() {
      // uncomment below and update the code to test the property scope
      //var instance = new OxdServer.GetClientTokenParams();
      //expect(instance).to.be();
    });

    it('should have the property clientId (base name: "client_id")', function() {
      // uncomment below and update the code to test the property clientId
      //var instance = new OxdServer.GetClientTokenParams();
      //expect(instance).to.be();
    });

    it('should have the property clientSecret (base name: "client_secret")', function() {
      // uncomment below and update the code to test the property clientSecret
      //var instance = new OxdServer.GetClientTokenParams();
      //expect(instance).to.be();
    });

    it('should have the property authenticationMethod (base name: "authentication_method")', function() {
      // uncomment below and update the code to test the property authenticationMethod
      //var instance = new OxdServer.GetClientTokenParams();
      //expect(instance).to.be();
    });

    it('should have the property algorithm (base name: "algorithm")', function() {
      // uncomment below and update the code to test the property algorithm
      //var instance = new OxdServer.GetClientTokenParams();
      //expect(instance).to.be();
    });

    it('should have the property keyId (base name: "key_id")', function() {
      // uncomment below and update the code to test the property keyId
      //var instance = new OxdServer.GetClientTokenParams();
      //expect(instance).to.be();
    });

  });

}));
