/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OxdServer);
  }
}(this, function(expect, OxdServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OxdServer.JsonWebKey();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JsonWebKey', function() {
    it('should create an instance of JsonWebKey', function() {
      // uncomment below and update the code to test JsonWebKey
      //var instance = new OxdServer.JsonWebKey();
      //expect(instance).to.be.a(OxdServer.JsonWebKey);
    });

    it('should have the property kid (base name: "kid")', function() {
      // uncomment below and update the code to test the property kid
      //var instance = new OxdServer.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property kty (base name: "kty")', function() {
      // uncomment below and update the code to test the property kty
      //var instance = new OxdServer.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property use (base name: "use")', function() {
      // uncomment below and update the code to test the property use
      //var instance = new OxdServer.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property keyOps (base name: "key_ops")', function() {
      // uncomment below and update the code to test the property keyOps
      //var instance = new OxdServer.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property alg (base name: "alg")', function() {
      // uncomment below and update the code to test the property alg
      //var instance = new OxdServer.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property exp (base name: "exp")', function() {
      // uncomment below and update the code to test the property exp
      //var instance = new OxdServer.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property x5c (base name: "x5c")', function() {
      // uncomment below and update the code to test the property x5c
      //var instance = new OxdServer.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property x5t (base name: "x5t")', function() {
      // uncomment below and update the code to test the property x5t
      //var instance = new OxdServer.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property x5tS256 (base name: "x5t#S256")', function() {
      // uncomment below and update the code to test the property x5tS256
      //var instance = new OxdServer.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property x5u (base name: "x5u")', function() {
      // uncomment below and update the code to test the property x5u
      //var instance = new OxdServer.JsonWebKey();
      //expect(instance).to.be();
    });

  });

}));
