/**
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OxdServer);
  }
}(this, function(expect, OxdServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OxdServer.UmaRpGetRptParams();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UmaRpGetRptParams', function() {
    it('should create an instance of UmaRpGetRptParams', function() {
      // uncomment below and update the code to test UmaRpGetRptParams
      //var instance = new OxdServer.UmaRpGetRptParams();
      //expect(instance).to.be.a(OxdServer.UmaRpGetRptParams);
    });

    it('should have the property oxdId (base name: "oxd_id")', function() {
      // uncomment below and update the code to test the property oxdId
      //var instance = new OxdServer.UmaRpGetRptParams();
      //expect(instance).to.be();
    });

    it('should have the property ticket (base name: "ticket")', function() {
      // uncomment below and update the code to test the property ticket
      //var instance = new OxdServer.UmaRpGetRptParams();
      //expect(instance).to.be();
    });

    it('should have the property claimToken (base name: "claim_token")', function() {
      // uncomment below and update the code to test the property claimToken
      //var instance = new OxdServer.UmaRpGetRptParams();
      //expect(instance).to.be();
    });

    it('should have the property claimTokenFormat (base name: "claim_token_format")', function() {
      // uncomment below and update the code to test the property claimTokenFormat
      //var instance = new OxdServer.UmaRpGetRptParams();
      //expect(instance).to.be();
    });

    it('should have the property pct (base name: "pct")', function() {
      // uncomment below and update the code to test the property pct
      //var instance = new OxdServer.UmaRpGetRptParams();
      //expect(instance).to.be();
    });

    it('should have the property rpt (base name: "rpt")', function() {
      // uncomment below and update the code to test the property rpt
      //var instance = new OxdServer.UmaRpGetRptParams();
      //expect(instance).to.be();
    });

    it('should have the property scope (base name: "scope")', function() {
      // uncomment below and update the code to test the property scope
      //var instance = new OxdServer.UmaRpGetRptParams();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new OxdServer.UmaRpGetRptParams();
      //expect(instance).to.be();
    });

  });

}));
